export const INSERT_TASK_QUERY = `INSERT INTO tasks (
    schedule,
    task_start,
    task_end,
    task_status,
    task_time_allocated,
    assigned_to,
    customer,
    task_id,
    uid,
    task_tag,
    task_title,
    task_des,
    instructions,
    notes,
    location,
    gps_coords,
    sched_day,
    sched_time
) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
